### ISSUE TITLE
index.d.ts is not included in the published npm package

### ISSUE THREAD

**Issue by regevbr** [wooorm/linked-list#12]
index.d.ts is not included in the published npm package

**Comment by regevbr** [comment]
also need to make the Item generic...

**Comment by wooorm** [comment]
@regevbr Changing things should happen before cutting a release. Could you open a PR if you want the above in the release?

**Comment by regevbr** [comment]
sure

**Comment by wooorm** [comment]
Released [`2.0.0`](https://github.com/wooorm/linked-list/releases/tag/2.0.0)!
