### ISSUE TITLE
Question: Can I republish library with some changes?

### ISSUE THREAD

**Issue by aikrom** [wooorm/linked-list#17]
Hi, I used your code from your library to create mine with minor modifications and published it under a different name ([@aintts/linked-list](https://www.npmjs.com/package/@aintts/linked-list)). I have added links to this repository, kept the license as it was, and listed you as the author.

Changes:
- Created a project from scratch using [tsdx](https://tsdx.io/).
- Rewrote all the code to Typescript.
- Rewrote tests using Jest.
- Added observer pattern (in test mode).

If you don't want me to republish the library, please let me know - I will remove it immediately.

**Comment by wooorm** [comment]
The code here is open source, that means you are allowed to create a fork, given that you keep the license info (which you did).
I do suggest adding the current year and your own name too, though:

```
Copyright (c) 2021 Your Name <your-email@gmail.com>
Copyright (c) 2014 Titus Wormer <tituswormer@gmail.com>
```
