### ISSUE TITLE
tail should always be set for non-empty lists

### ISSUE THREAD

**Issue by GregLoring** [wooorm/linked-list#22]
List `tail` should always be set for non-empty lists, _including_ when a list has only one item.  In the one item case, `head` and `tail` should be the same, both pointing to the single item in the list.  This preserves the defining capabilities of a doubly linked list:
- start at the `head` and walk forward through the entire list using `next`
- start at the `tail` and walk backward through the entire list using `prev`

At this time, `linked-list` sets the `tail` to `null` if there is only one item in the list.  This is incorrect, IMO, and difficult to work with.

Consider using List to implement a FIFO queue.
- The writer is obvious.  It calls `list.prepend(item)` whenever it needs to add an item to the queue.
- The reader should also be obvious.  It _should_ be able to drain the queue with this simple loop:
```javascript
while (list.tail) {
  process(list.tail.detach())
}
```

Sadly, the current implementation of List requires something like
```javascript
while (list.size > 0) {
  const item = (list.size === 1) ? list.head : list.tail
  process(item.detach())
}
```
which is uglier, but maybe more clear, or
```javascript
while (list.tail || list.head) {
  process((list.tail || list.head).detach())
}
```
which is prettier, but mysterious.

Both of these loops are implementation specific, and I find them difficult to understand.

There is special case code [here](https://github.com/wooorm/linked-list/blob/ea543fbe50f069fd2628cb54f5bf8e20a1161213/index.js#L129) to make `tail` go away when the list shrinks to a single item, and two one-liners are omitted [here](https://github.com/wooorm/linked-list/blob/ea543fbe50f069fd2628cb54f5bf8e20a1161213/index.js#L211) and [here](https://github.com/wooorm/linked-list/blob/ea543fbe50f069fd2628cb54f5bf8e20a1161213/index.js#L246) to leave `tail` null when the first item is added.  This behavior is also asserted in `test.js`, so I'm guessing there was a reason for this null tail behavior.

Thoughts?

**Comment by GregLoring** [comment]
cool.  thanks for the speedy reply

**Comment by wooorm** [comment]
Is using `prev` fine for you?

**Comment by wooorm** [comment]
Closing :)
