### ISSUE TITLE
TypeScript definition

### ISSUE THREAD

**Issue by blakeembrey** [wooorm/linked-list#7]
Would you be interested in accepting a TypeScript definition for the library so people using TypeScript can get type safety? It's a separate file from the `.js` which will basically act as a header file only and I'd be happy to be a continual resource to help maintain it or respond to any queries.

**Comment by wooorm** [comment]
I think so, yeah! I’m wondering about maintaining it though. I guess this repo doesn’t change ever, so it’s fine.

Why not definitely typed? Also, as we’re talking, I’m interested in your opinion on https://github.com/syntax-tree/unist-ts/issues/1!

**Comment by blakeembrey** [comment]
DefinitelyTyped is nice, but requires a separate package and isn't kept in sync with the library. It's also kind of hard to contribute to and can result in long-tail packages being incorrect. My preference is always to have it in the library where possible, one such example is https://github.com/pillarjs/path-to-regexp. Especially when the package doesn't change much as this would.

I would also call this library a fundamental data type, so it'd be even more awesome to see TypeScript bundled when I want to get started quickly instead of looking around for TypeScript support.

**Comment by wooorm** [comment]
Totes. I’m open to this!

**Comment by regevbr** [comment]
Hi, the index.d.ts is not publish in the package - I opened an issue for it
