### ISSUE TITLE
Iterator support

### ISSUE THREAD

**Issue by blakeembrey** [wooorm/linked-list#8]
Would you be interested in adding first-class iterator support to the library? This would allow someone to use the linked list in places support iterations (e.g. `for (const item of list)`) or in iteration libraries (e.g. [`iterative`](https://github.com/blakeembrey/iterative)). You can also then use `Array.from(list)` to turn the linked list into an array, or use it in other places that support an iterator such as `Set()` and `Map()`.

This would likely be a breaking change, however, since it's an ES2015 feature.

Edit: Actually, it's probably easy enough to keep it backward compatible if needed - just more verbose.

**Comment by wooorm** [comment]
Ah, I guess it is about to change :p

I think I’d prefer this to be readable in simple JS, compared to es++. Let’s try it out as just an addition, instead of a whole rewrite!

**Comment by wooorm** [comment]
Also: I’m switching my projects to browserify with tinyify. The building and mangling isn’t very interesting other than we have them on the releases page, and can check if the size increases a lot there, tinyify should be able to understand this, but still I’d prefer no short hand props!
